# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_post_post_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=25)),
                ('engine_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol')], max_length=10)),
                ('year_of_fabrication', models.IntegerField()),
                ('kilometers', models.IntegerField()),
                ('state', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], max_length=10)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year_of_fabrication', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FurniturePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], max_length=10)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HousePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('bedroom', models.IntegerField()),
                ('Hall', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('swimming_pool', models.BooleanField()),
                ('house_service_type', models.CharField(choices=[('SALE', 'Sale'), ('RENT', 'Rent')], max_length=20)),
                ('house_type', models.CharField(choices=[('FLAT', 'Flat'), ('INDIVIDUAL', 'Individual'), ('BUILDING', 'Building')], max_length=20)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], max_length=10)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobAndServicePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LawnPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
