# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_autopost_electronicpost_furniturepost_housepost_jobandservicepost_lawnpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autopost',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='autopost',
            name='kilometers',
        ),
        migrations.AddField(
            model_name='autopost',
            name='chassis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='autopost',
            name='doors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autopost',
            name='engine_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autopost',
            name='exterior_color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='autopost',
            name='fuel',
            field=models.CharField(blank=True, choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('ELECTRIC', 'Electric')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='autopost',
            name='interior_color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='autopost',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autopost',
            name='transmission',
            field=models.CharField(blank=True, choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='electronicpost',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electronicpost',
            name='state',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('USED', 'Used')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='autopost',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housepost',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
