# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20180203_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('post', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='autopostphotourl',
            name='post',
        ),
        migrations.DeleteModel(
            name='AutoPostPhotoUrl',
        ),
    ]
