# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20180207_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='photourl',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
