# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_photourl_is_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photourl',
            old_name='post',
            new_name='post_id',
        ),
    ]
