# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20180207_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopost',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
