# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_autopost_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('town', models.CharField(max_length=250, null=True)),
                ('is_local', models.BooleanField(default=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('brand', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('state', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], max_length=10)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
