# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_mobilepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopost',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='autopost',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='autopost',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='http://via.placeholder.com/140x100', null=True),
        ),
        migrations.AlterField(
            model_name='autopost',
            name='town',
            field=models.CharField(default='Kinshasa', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mobilepost',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mobilepost',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mobilepost',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='http://via.placeholder.com/140x100', null=True),
        ),
        migrations.AlterField(
            model_name='mobilepost',
            name='town',
            field=models.CharField(default='Kinshasa', max_length=250, null=True),
        ),
    ]
