# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20180303_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepost',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='housepost',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='housepost',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='housepost',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='http://via.placeholder.com/140x100', null=True),
        ),
        migrations.AddField(
            model_name='housepost',
            name='town',
            field=models.CharField(default='Kinshasa', max_length=250, null=True),
        ),
    ]
