# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20180306_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='photourl',
            name='category_code',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
