# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_photourl_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopost',
            name='user_uid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='housepost',
            name='user_uid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mobilepost',
            name='user_uid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
