# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20180412_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopost',
            name='user_uid',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='housepost',
            name='user_uid',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mobilepost',
            name='user_uid',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
