# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20180512_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housepost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobilepost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
